---
title: "My Book"
output: 
     html_document:
       toc: true
       toc_depth: 2
       toc_float: true
---

I will write a really good book here.

# Section 1
My first project on the subject, “District Industry, Wealth Inequality, and Welfare under Trade Liberalization,” I explore how changes in levels of wealth inequality interact with the industrial performance and then influence candidates’ redistributive policy pledges. While many scholars have found that economic globalization has led to changes in the welfare policies put forward by governments and parties, we know little about the extent to which economic liberalization affects how individual candidates address welfare policies during campaigns to win votes. The existing literature shows that the industry composition of districts matters for legislators’ welfare preferences and voting behavior. In this project, I further consider how changes in the level of wealth inequality, which is found to be associated with trade liberalization by many scholars, interact with the industry composition and performance at the district-level and influence candidates’ redistributive welfare policy pledges in campaigns. I argue that candidates from districts with industries that lost more from trade liberalization and increased wealth inequality will promise more welfare pledges. I further contend that when the losing industry is consisted of the middle class within the district, candidates’ will present more redistributive pledges. I use the case of Korea, a small open economy, in which the government adopted various redistributive policies after trade liberalization for adversely affected industries, such as subsidies for small and medium-sized businesses. Using the district-level data of industry performance, wealth inequality, and candidates' campaign documents, this project will contribute to our understanding of candidates' responsiveness in the era of trade liberalization and increasing wealth inequality. 

I am also interested in the effects of wealth inequality on the responsiveness by different genders of the representatives. In my working paper, “Gendered Campaign Brochures: Gender Differences in Responsiveness to Inequality and Electoral Success of Female Candidates in Korean Elections,” I explore the determinants of the electoral success of female candidates under wealth inequality. While we know that party, personal qualification, and incumbency matter for female candidates’ electoral performance, we know little about how female candidates differ from male counterparts regarding responsiveness to inequality-related issues and how the difference affects the electoral outcome. I argue that women who respond more strongly to inequality-related issues of their district than her co-partisan male candidates can enter male-dominant politics. For this paper, I use over 600 campaign brochures from the Korean local legislative elections in 2014 and 2018 under a multi-member district system, which allows us to control for the party effect. I explore how female candidates’ responsiveness differs from their co-partisan male candidates running for the same district and whether female candidates who delivered more inequality-related issues could gain more votes than their male co-partisan rival. My preliminary findings from the text analysis show that women and men do not differ in responding to inequality. Next, I will employ a survey experiment to understand the causal mechanism behind the relationship between responsiveness and electoral outcomes.

# Section 2
Lastly, I have a growing research interest in the effect of increasingly difficult housing affordability on the political attitudes of the middle class. On the subject, my paper based on cross-country analysis, “Can't Keep Up: Housing Affordability and Satisfaction with Democracy,” examines how housing prices that have increased sharply in recent years around the world combined with stagnant wages affect individuals' satisfaction with democracy. Because a house can work as insurance for emergent needs or retired life, individuals, those who cannot afford to buy a house with stagnating income can be anxious about their future and thus, I argue, can be dissatisfied with politics and democracy. However, because the electoral system could influence the political process of economic policy-making, I further argue that the electoral system will mediate the impact of increased House-Price-to-Income Ratio on individuals’ satisfaction with democracy. My analysis using the Comparative Study of Electoral Systems data which are matched with housing affordability and income data supports the argument.

# Section 3

I am also interested in the heterogeneous welfare attitudes among homeowners. Previous studies have documented that homeowners or those who experienced house value appreciation oppose more redistribution because owning a home serves as private insurance. However, less is known about the conditions under which homeowners differ in their attitudes towards the welfare state. In my working paper, “No Country for Old Men: Homeownership and Welfare State in Korea,” I contend that what matters is not only homeownership but also the life cycle as well as house values in order for ownership to work like insurance. I examine how homeownership affects the preferences for the provision of public goods such as pension benefits across different generations, arguing that not all homeowners will necessarily support more redistribution, splitting policy preferences within generations, especially among elderly citizens. It also explores how house value affects attitudes towards the state welfare capacity. I argue that individuals’ attitudes in state welfare is determined by house values, but the effect of house prices (or house price appreciation) will depend on if the house price is enough to work as private insurance. Using two survey data from Korea, findings support these arguments. To provide a more rigorous causal analysis, I plan to plot a survey experiment in the fall of 2022.